name: Metrics
on:
  schedule: 
    - cron: "0 0 * * *" # 매일 자동 업데이트
  workflow_dispatch: # 수동 실행 가능
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "repositories"
          plugin_isocalendar: yes

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "repositories"
          plugin_languages: yes
          plugin_languages_details: "percentage"

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "repositories"
          plugin_starlists: yes

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "repositories"
          plugin_achievements: yes
